name: Release new version

on:
  push:
    branches:
      - readme
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }} Environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/coverage.txt

      - name: Coverage Test
        run: |
          coverage run runtests.py
          coverage report

      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "STRIP_RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          python setup.py sdist bdist_wheel

      - name: Archive wheel artifacts file
        uses: actions/upload-artifact@v3
        with:
          name: django-dysession-${{ env.RELEASE_VERSION }}-artifacts
          path: |
            dist/*
